package br.gov.caixa.sidpn.api.swagger.enums;

public enum EnumWarrantyType {
    SEM_TIPO_GARANTIA,
    CESSAO_DIREITOS_CREDITORIOS,
    CAUCAO,
    PENHOR,
    ALIENACAO_FIDUCIARIA,
    HIPOTECA,
    OPERACOES_GARANTIDAS_PELO_GOVERNO,
    OUTRAS_GARANTIAS_NAO_FIDEJUSSORIAS,
    SEGUROS_ASSEMELHADOS,
    GARANTIA_FIDEJUSSORIA,
    BENS_ARRENDADOS,
    GARANTIAS_INTERNACIONAIS,
    OPERACOES_GARANTIDAS_OUTRAS_ENTIDADES,
    ACORDOS_COMPENSACAO;
}