package br.gov.caixa.sidpn.api.swagger.enums;

public enum EnumSiobaPermissions {

	UNARRANGED_ACCOUNTS_OVERDRAFT_READ,
	UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ,
	UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ,
	UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ;

}
